project_name: flow
before:
  hooks:
    - go mod tidy

builds:
  - id: flow
    main: .
    binary: flow
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: tgz
    builds: [flow]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
  - id: zipwin
    builds: [flow]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
